var sss = {
   "name":"root",
   "children":[
      {
         "name":"ru",
         "children":[
            {
               "name":"agentlab",
               "children":[
                  {
                     "name":"maia",
                     "children":[
                        {
                           "name":"context",
                           "children":[
                              {
                                 "name":"injector",
                                 "children":[
                                    {
                                       "name":"e4",
                                       "children":[
                                          {
                                             "name":"E4MaiaContext"
                                          }
                                       ]
                                    }
                                 ]
                              },
                              {
                                 "name":"initializer",
                                 "children":[
                                    {
                                       "name":"MaiaContextInitializerService"
                                    }
                                 ]
                              },
                              {
                                 "name":"naming",
                                 "children":[
                                    {
                                       "name":"uuid",
                                       "children":[
                                          {
                                             "name":"UuidNameGenerator"
                                          }
                                       ]
                                    }
                                 ]
                              },
                              {
                                 "name":"typing",
                                 "children":[
                                    {
                                       "name":"behaviour",
                                       "children":[
                                          {
                                             "name":"MaiaBehaviourContextFactory"
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        },
                        {
                           "name":"launcher",
                           "children":[
                              {
                                 "name":"AgentExample"
                              }
                           ]
                        },
                        {
                           "name":"execution",
                           "children":[
                              {
                                 "name":"MaiaExecutorUnfixedRunnable"
                              },
                              {
                                 "name":"MaiaExecutorService"
                              },
                              {
                                 "name":"lifecycle",
                                 "children":[
                                    {
                                       "name":"fipa",
                                       "children":[
                                          {
                                             "name":"FipaLifecycleScheme"
                                          }
                                       ]
                                    },
                                    {
                                       "name":"LifecycleService"
                                    },
                                    {
                                       "name":"LifecycleState"
                                    }
                                 ]
                              },
                              {
                                 "name":"scheduler",
                                 "children":[
                                    {
                                       "name":"sequence",
                                       "children":[
                                          {
                                             "name":"SequenceContextScheduler"
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         ]
      },
      {
         "name":"java",
         "children":[
            {
               "name":"lang",
               "children":[
                  {
                     "name":"String"
                  }
               ]
            }
         ]
      },
      {
         "name":""
      }
   ]
}