package ru.agentlab.maia;

public enum EventType {

	/*-------------------- Addition events --------------------*/

	ADDED_CLASS_ASSERTION,

	ADDED_DATA_PROPERTY_ASSERTION,

	ADDED_NEGATIVE_DATA_PROPERTY_ASSERTION,

	ADDED_OBJECT_PROPERTY_ASSERTION,

	ADDED_NEGATIVE_OBJECT_PROPERTY_ASSERTION,

	ADDED_MESSAGE,

	ADDED_ROLE,

	ADDED_EXTERNAL_EVENT,

	/*-------------------- Removes events --------------------*/

	REMOVED_CLASS_ASSERTION,

	REMOVED_DATA_PROPERTY_ASSERTION,

	REMOVED_NEGATIVE_DATA_PROPERTY_ASSERTION,

	REMOVED_OBJECT_PROPERTY_ASSERTION,

	REMOVED_NEGATIVE_OBJECT_PROPERTY_ASSERTION,

	REMOVED_MESSAGE, REMOVED_ROLE,

	/*-------------------- Add Goals events --------------------*/

	GOAL_CLASS_ASSERTION,

	GOAL_DATA_PROPERTY_ASSERTION,

	GOAL_NEGATIVE_DATA_PROPERTY_ASSERTION,

	GOAL_OBJECT_PROPERTY_ASSERTION,

	GOAL_NEGATIVE_OBJECT_PROPERTY_ASSERTION,

	/*-------------------- Failed Goals events --------------------*/

	FAILED_CLASS_ASSERTION,

	FAILED_DATA_PROPERTY_ASSERTION,

	FAILED_NEGATIVE_DATA_PROPERTY_ASSERTION,

	FAILED_OBJECT_PROPERTY_ASSERTION,

	FAILED_NEGATIVE_OBJECT_PROPERTY_ASSERTION,

	UNHANDLED_MESSAGE,

	RESOLVED_ROLE,

	UNRESOLVED_ROLE

}
