package ru.agentlab.maia.event;

public enum EventType {

	AGENT_BELIEF_ADDED,

	AGENT_BELIEF_CLASS_ASSERTION_ADDED,

	AGENT_BELIEF_CLASS_ASSERTION_REMOVED,

	AGENT_BELIEF_OBJECT_PROPERTY_ASSERTION_ADDED,

	AGENT_BELIEF_OBJECT_PROPERTY_ASSERTION_REMOVED,

	AGENT_BELIEF_DATA_PROPERTY_ASSERTION_ADDED,

	AGENT_BELIEF_DATA_PROPERTY_ASSERTION_REMOVED,

	AGENT_BELIEF_CLASS_ADDED,

	AGENT_BELIEF_REMOVED,

	AGENT_GOAL_ADDED,

	AGENT_GOAL_STARTED,

	AGENT_GOAL_FINISHED,

	AGENT_GOAL_FAILED,

	AGENT_GOAL_REMOVED,

	AGENT_PLAN_ADDED,

	AGENT_PLAN_STARTED,

	AGENT_PLAN_FINISHED,

	AGENT_PLAN_FAILED,

	AGENT_PLAN_REMOVED,

	AGENT_MESSAGE_ADDED,

	AGENT_MESSAGE_REMOVED,

	CONTAINER_CHILD_ADDED,

	CONTAINER_CHILD_REMOVED,

	CONTAINER_SERVICE_ADDED,

	CONTAINER_SERVICE_REMOVED,

	CONTAINER_AGENT_ADDED,

	CONTAINER_AGENT_REMOVED

}
