package ru.agentlab.maia.agent.annotation;

public enum AxiomType {
	
	ANNOTATION_ASSERTION, 
	ANNOTATION_PROPERTY_DOMAIN, 
	ANNOTATION_PROPERTY_RANGE, 
	ASYMMETRIC_OBJECT_PROPERTY, 
	CLASS_ASSERTION, 
	DATATYPE_DEFINITION, 
	DATA_PROPERTY_ASSERTION, 
	DATA_PROPERTY_DOMAIN, 
	DATA_PROPERTY_RANGE, 
	DIFFERENT_INDIVIDUALS, 
	DISJOINT_CLASSES, 
	DISJOINT_DATA_PROPERTIES, 
	DISJOINT_OBJECT_PROPERTIES, 
	DISJOINT_UNION, 
	EQUIVALENT_CLASSES, 
	EQUIVALENT_OBJECT_PROPERTIES, 
	EQUIVALENT_DATA_PROPERTIES, 
	FUNCTIONAL_DATA_PROPERTY, 
	FUNCTIONAL_OBJECT_PROPERTY, 
	INVERSE_FUNCTIONAL_OBJECT_PROPERTY, 
	INVERSE_OBJECT_PROPERTIES, 
	IRREFLEXIVE_OBJECT_PROPERTY, 
	NEGATIVE_DATA_PROPERTY_ASSERTION, 
	NEGATIVE_OBJECT_PROPERTY_ASSERTION, 
	OBJECT_PROPERTY_ASSERTION, 
	OBJECT_PROPERTY_DOMAIN, 
	OBJECT_PROPERTY_RANGE, 
	REFLEXIVE_OBJECT_PROPERTY, 
	SAME_INDIVIDUAL, 
	SUBCLASS_OF, 
	SUB_ANNOTATION_PROPERTY_OF, 
	SUB_DATA_PROPERTY, 
	SUB_OBJECT_PROPERTY, 
	SUB_PROPERTY_CHAIN_OF, 
	SYMMETRIC_OBJECT_PROPERTY, 
	TRANSITIVE_OBJECT_PROPERTY, 
	DECLARATION, 
	SWRL_RULE, 
	HAS_KEY;

	public int getArity() {
		// TODO Auto-generated method stub
		return 0;
	}

}
